stages:
    - preparation
    - 'PHP 8.1'
    - 'PHP 8.2'


default:
    before_script:
        - apt-get update -yqq
        - apt-get install -yqq git libxml2-dev libzip-dev zip unzip

        # Install PHP extensions
        - docker-php-ext-install xml zip


# Job template
.composer:
    stage: preparation
    script:
        - php --version
        # Install composer
        - curl -sS https://getcomposer.org/installer | php
        # Install all project dependencies
        - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    artifacts:
        paths:
            - vendor/
        expire_in: 1 days
        when: always
    cache:
        paths:
            - vendor/


# Job template: Run code sniffer
.phpcs:
    script:
        - php --version
        - vendor/bin/phpcs src/ --standard=PSR12 --extensions=php --report=junit > phpcs-report.xml
    artifacts:
        reports:
            junit:
                - phpcs-report.xml


# Job template: Run static analysis
.phpstan:
    script:
        - php --version
        - vendor/bin/phpstan analyse --error-format=junit --no-progress -c ./phpstan.neon > phpstan-report.xml
    artifacts:
        reports:
            junit:
                - phpstan-report.xml

# Job template: Run tests
.phpunit:
    # Set any variables we need
    variables:
        XDEBUG_MODE: coverage
    # If Xdebug was installed you can generate a coverage report and see code coverage metrics.
    script:
        - php --version
        - vendor/bin/phpunit --configuration phpunit.xml --log-junit phpunit-report.xml --coverage-text --colors=never --coverage-html=coverage/
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    artifacts:
        reports:
            junit: phpunit-report.xml
        when: always
        paths:
            - coverage
        expire_in: 30 days


# PHP 8.1
.php8.1:
    image: php:8.1
    stage: 'PHP 8.1'
    before_script:
        - !reference [ default, before_script ]
        # Install & enable Xdebug for code coverage reports
        - pecl install xdebug-3.2.1
        - docker-php-ext-enable xdebug

composer:8.1:
    extends:
        - .php8.1
        - .composer

.php8.1-test:
    extends:
        - .php8.1
    needs: [ 'composer:8.1' ]

phpcs:8.1:
    extends:
        - .php8.1-test
        - .phpcs

phpstan:8.1:
    extends:
        - .php8.1-test
        - .phpstan

phpunit:8.1:
    extends:
        - .php8.1-test
        - .phpunit


# PHP 8.2
.php8.2:
    image: php:8.2
    stage: 'PHP 8.2'
    before_script:
        - !reference [ default, before_script ]
        # Install & enable Xdebug for code coverage reports
        - pecl install xdebug-3.2.1
        - docker-php-ext-enable xdebug

composer:8.2:
    extends:
        - .php8.2
        - .composer

.php8.2-test:
    extends:
        - .php8.2
    needs: [ 'composer:8.2' ]

phpcs:8.2:
    extends:
        - .php8.2-test
        - .phpcs

phpstan:8.2:
    extends:
        - .php8.2-test
        - .phpstan

phpunit:8.2:
    extends:
        - .php8.2-test
        - .phpunit
